FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
        PORT=8080 \
            MCP_TRANSPORT=streamable-http

ARG CRONOMETER_USERNAME
ARG CRONOMETER_PASSWORD
ARG MCP_BASE_URL
ARG MCP_OAUTH_CLIENT_ID
ARG MCP_OAUTH_CLIENT_SECRET
ARG MCP_AUTH_TOKEN

ENV CRONOMETER_USERNAME=${CRONOMETER_USERNAME} \
    CRONOMETER_PASSWORD=${CRONOMETER_PASSWORD} \
    MCP_BASE_URL=${MCP_BASE_URL} \
    MCP_OAUTH_CLIENT_ID=${MCP_OAUTH_CLIENT_ID} \
    MCP_OAUTH_CLIENT_SECRET=${MCP_OAUTH_CLIENT_SECRET} \
    MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}

            WORKDIR /app

            RUN pip install uv

            COPY pyproject.toml README.md ./
            COPY src ./src

            RUN uv pip install --system .

            CMD ["sh", "-c", "cronometer-api-mcp"]
            
